name       : mate-sensors-applet
version    : 1.20.1
release    : 8
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-sensors-applet-1.20.1.tar.xz : bd00e792ec3948bf895c8ff590184da30fa5614bc6969d450cfc8381a51cd952
license    : GPL-2.0
component  : desktop.mate
summary    : Sensors applet for MATE Panel
description: |
    MATE Sensors Applet is an applet for the MATE Panel to display
    readings from hardware sensors, including CPU temperature, fan speeds
    and voltage readings under Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - pkgconfig(x11)
    - lm_sensors-devel
    - itstool
rundeps    :
    - udisks
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

