name       : mate-sensors-applet
version    : 1.22.1
release    : 13
source     :
    - https://github.com/mate-desktop/mate-sensors-applet/archive/v1.22.1.tar.gz : 05d27ffa53b610b8bde518118718a7072d926638819df1e12bdc6eb47da357af
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Sensors applet for MATE Panel
description: |
    MATE Sensors Applet is an applet for the MATE Panel to display
    readings from hardware sensors, including CPU temperature, fan speeds
    and voltage readings under Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - pkgconfig(x11)
    - lm_sensors-devel
    - itstool
    - mate-common
    - yelp-tools
rundeps    :
    - udisks
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
