name       : mate-sensors-applet
version    : 1.20.3
release    : 11
source     :
    - https://github.com/mate-desktop/mate-sensors-applet/archive/v1.20.3.tar.gz : f2cf249b73801a899d821cab2ac7c54a1401000ccf592adcf247e51eb56131dc
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Sensors applet for MATE Panel
description: |
    MATE Sensors Applet is an applet for the MATE Panel to display
    readings from hardware sensors, including CPU temperature, fan speeds
    and voltage readings under Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - pkgconfig(x11)
    - lm_sensors-devel
    - itstool
    - mate-common
    - yelp-tools
rundeps    :
    - udisks
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
