name       : mate-sensors-applet
version    : 1.16.0
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-sensors-applet-1.16.0.tar.xz : 878cef0dddc3f77b143e04e5d01f9057fa8a387d1f2bb4ee4f1f5123143ab127
license    : GPL-2.0
component  : desktop.mate
summary    : Sensors applet for MATE Panel
description: |
    MATE Sensors Applet is an applet for the MATE Panel to display
    readings from hardware sensors, including CPU temperature, fan speeds
    and voltage readings under Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libatasmart)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - pkgconfig(x11)
    - libxslt
    - lm_sensors-devel
    - itstool
rundeps    :
    - udisks
setup      : |
    %configure --with-gtk=3.0 --enable-udisks --enable-libnotify
build      : |
    %make
install    : |
    %make_install
