name       : mate-sensors-applet
version    : 1.22.0
release    : 12
source     :
    - https://github.com/mate-desktop//mate-sensors-applet/archive/v1.22.0.tar.gz : 1c7e6bfffb952a11083819a74906f483856b501c1860ef77007db2ab453c2ac4
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Sensors applet for MATE Panel
description: |
    MATE Sensors Applet is an applet for the MATE Panel to display
    readings from hardware sensors, including CPU temperature, fan speeds
    and voltage readings under Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - pkgconfig(x11)
    - lm_sensors-devel
    - itstool
    - mate-common
    - yelp-tools
rundeps    :
    - udisks
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
