name       : mate-sensors-applet
version    : 1.24.0
release    : 14
source     :
    - https://github.com/mate-desktop/mate-sensors-applet/archive/v1.24.0.tar.gz : 272e475154e43e22a7d49e7045b02b976fc2a724fbc6abf3072085c57b576693
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Sensors applet for MATE Panel
description: |
    MATE Sensors Applet is an applet for the MATE Panel to display
    readings from hardware sensors, including CPU temperature, fan speeds
    and voltage readings under Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - pkgconfig(x11)
    - lm_sensors-devel
    - itstool
    - mate-common
    - yelp-tools
rundeps    :
    - udisks
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
