name       : mate-sensors-applet
version    : 1.18.0
release    : 3
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-sensors-applet-1.18.0.tar.xz : da37ced95eb95699d1ad8e6fad47a8fa721bd0f99ea007203b2ae329606e5b20
license    : GPL-2.0
component  : desktop.mate
summary    : Sensors applet for MATE Panel
description: |
    MATE Sensors Applet is an applet for the MATE Panel to display
    readings from hardware sensors, including CPU temperature, fan speeds
    and voltage readings under Linux.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libatasmart)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - pkgconfig(x11)
    - libxslt
    - lm_sensors-devel
    - itstool
rundeps    :
    - udisks
setup      : |
    %configure --with-gtk=3.0 --enable-udisks --enable-libnotify
build      : |
    %make
install    : |
    %make_install
